### ISSUE TITLE
Brew Packages

### ISSUE THREAD

**Issue by istx25** [istx25/dotfiles#1]
The brew packages I use are: gifsicle, hub, tree, brew-cask-completion, gmp, hugo, libtasn1, pinentry, wget, carthage, gnupg, keybase, libusb, pinentry-mac, gnupg21, libusb-compat, pkg-config, xvid, cowsay, gnutls, ffmpeg, go, python, gpg-agent, node (npm, etc), hr.

**Comment by trmml** [comment]
Just added these in [Brewfile](https://github.com/istx25/dotfiles/blob/master/Brewfile).

Added in [6f908e3](https://github.com/istx25/dotfiles/commit/6f908e3).

**Comment by istx25** [comment]
Cool, thanks!
