### ISSUE TITLE
Add git config --global push.default current

### ISSUE THREAD

**Issue by istx25** [istx25/Dotfiles#18]
Hi @trmml. I was wondering if you could help me setup my dotfiles so `git config --global push.default` is set by default every time I setup a new computer. This basically prevents you from having to specify your pushing to origin all the time when you create a new branch and do `git push`.

**Comment by trmml** [comment]
You could just throw it in your `fish_prompt`. Wrap it in `eval`, so `eval "git config --global push.default"`
