### ISSUE TITLE
Ruby Gems

### ISSUE THREAD

**Issue by istx25** [istx25/dotfiles#2]
The gems I use are pry, cocoapods, xcpretty, lifx, fastlane, synx, xcode-install, bundler, heroku (i think is a gem).

**Comment by trmml** [comment]
Just added these in [Gemfile](https://github.com/istx25/dotfiles/blob/master/Gemfile).

Added in [6f908e3](https://github.com/istx25/dotfiles/commit/6f908e3).

**Comment by istx25** [comment]
Cool, thanks!
