### ISSUE TITLE
Just a few things

### ISSUE THREAD

**Issue by istx25** [istx25/dotfiles#4]
I was looking through this and noticed a few things that I'd like to bring up.

- https://github.com/istx25/dotfiles/blob/master/.gitignore

Wouldn't this be `.gitconfig` not `.gitignore`?

- osx.fish

Rename to macOS since OS X was renamed to that.

**Comment by istx25** [comment]
Does homesick still work with fish? Could we use that?

**Comment by trmml** [comment]
@istx25 whoops, yeah it should be `.gitconfig`, my bad. I'll fix that right now.

Also, there are homesick forks that sort of work with fish in a hack-ey way, but support isn't really there yet, as far as I know. If you want to try it we could, but I can't guarantee everything will work as it would in Bash.

**Comment by istx25** [comment]
Makes sense. We don't have to use homesick if it doesn't work as expected though it would be cool to find something similar or something idk.

**Comment by trmml** [comment]
I'll look around to see if I can find an alternative that's more well supported for fish.
