### ISSUE TITLE
Error: Invalid Brewfile

### ISSUE THREAD

**Issue by istx25** [istx25/Dotfiles#6]
@trmml: ran `bash setup.sh` on my new computer and got this error.

```
Error: Invalid Brewfile: (eval):27: syntax error, unexpected tIDENTIFIER, expecting end-of-input
brew 'cowsay'
```

Can you help me fix this?

**Comment by istx25** [comment]
Oh. I think it has to do with:

```
brew 'xvid
brew 'cowsay'
```

`brew 'xvid'` didn't have the trailing '.

**Comment by trmml** [comment]
Forgot an apostrophe to close one of the strings, just fixed it 👍

**Comment by istx25** [comment]
Thanks!!
